language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "Test for TravisCI install"

# Scripts to be run such as tests
before_script:
  - echo "Test for TravisCI before_script"

script:
  - docker --version # print the version for logging
  - docker build -t uda3-app-feed:v$TRAVIS_BUILD_NUMBER ./udagram-api-feed
  - docker tag uda3-app-feed:v$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/uda3-app-feed:v$TRAVIS_BUILD_NUMBER

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/uda3-app-feed
